### ISSUE TITLE
美化界面

### ISSUE THREAD

**Issue by Extrwave** [wickedll/genshin_draw_analysis#11]
你好，考虑做一下分析界面的优化吗，比如将角色的头像显示出来，四星数目可以不用显示，类似于![](https://drive.ethreal.cn/Loader/B68CDCE2A9A7B8792AC828A52F1BF4F6.jpg)

**Comment by wickedll** [comment]
可以考虑  加入待办

**Comment by wickedll** [comment]
先这样 后期再调整

**Comment by wickedll** [comment]
![B2FZBO$)QM3`V`DGZ6Y7V)I](https://user-images.githubusercontent.com/29485174/164972364-af48acb0-311f-4ebb-a028-96ed81ed3670.gif)
