### ISSUE TITLE
多个抽卡记录链接无法分析问题

### ISSUE THREAD

**Issue by Fuyumachi** [wickedll/genshin_draw_analysis#2]
先后设置完两个不同的抽卡记录链接，使用[draw_analysis]Bot只会分析第一个设置的，第二个设置的链接不会覆盖也不会被分析。

**Comment by wickedll** [comment]
> 先后设置完两个不同的抽卡记录链接，使用[draw_analysis]Bot只会分析第一个设置的，第二个设置的链接不会覆盖也不会被分析。

emmm，我设置的是会覆盖的

**Comment by wickedll** [comment]
> 先后设置完两个不同的抽卡记录链接，使用[draw_analysis]Bot只会分析第一个设置的，第二个设置的链接不会覆盖也不会被分析。

找到问题了 待会儿提交个版本

**Comment by wickedll** [comment]
> 先后设置完两个不同的抽卡记录链接，使用[draw_analysis]Bot只会分析第一个设置的，第二个设置的链接不会覆盖也不会被分析。

[修复无法覆盖url问题](https://github.com/wickedll/genshin_draw_analysis/commit/2d314839252cf27c435e88c9ae84abbf35d44722)已修复
