### ISSUE TITLE
启动bot时，插件报错

### ISSUE THREAD

**Issue by MrAgNO3** [wickedll/genshin_draw_analysis#27]
![image](https://user-images.githubusercontent.com/74173773/218242603-50003dcd-e819-4622-8231-c7db9dac03d2.png)

**Comment by wickedll** [comment]
把项目根目录下的tsconfig.json的
![image](https://user-images.githubusercontent.com/29485174/218243024-443df783-2acc-461e-9986-21ddedb75a61.png)
编译之后的版本目标改成 `ESNEXT `这个看一下
