### ISSUE TITLE
URL输入错误

### ISSUE THREAD

**Issue by Annabel0530** [wickedll/genshin_draw_analysis#3]
试了试几个公众号小程式都可以使用  BOT显示错误  用的是IOS抓包获取的URL

**Comment by wickedll** [comment]
> 试了试几个公众号小程式都可以使用 BOT显示错误 用的是IOS抓包获取的URL

url有包含index.html?  和 &game_biz=hk4e_cn 吗

**Comment by Annabel0530** [comment]
后者有

**Comment by wickedll** [comment]
> 后者有

那你应该直接抓到的是https://hk4e-api.mihoyo.com/event/gacha_info/api/getGachaLog?这个接口吗

**Comment by Annabel0530** [comment]
> 

对的

**Comment by wickedll** [comment]
https://webstatic.mihoyo.com/hk4e/event/e20190909gacha/index.html? 有没有这种的web页呢  这边用的是web页 再去串接口

**Comment by wickedll** [comment]
或者我之后改成两种都支持看看

**Comment by wickedll** [comment]
也可以把抓到的接口参数 直接串到我上面发的那个html链接后面 发给bot就可以了

**Comment by Annabel0530** [comment]
可以找到  ios抓包的话不在前排  提交url算是解决了
想知道BOT能不能上传表格呢  我姑且是把自己开服至今的抽卡记录都有保存  如果麻烦的话还是算了

**Comment by wickedll** [comment]
> 可以找到 ios抓包的话不在前排 提交url算是解决了 想知道BOT能不能上传表格呢 我姑且是把自己开服至今的抽卡记录都有保存 如果麻烦的话还是算了

这个我后面看看  能不能接收表格文件读取 或者json文件
