### ISSUE TITLE
提示visit too frequently

### ISSUE THREAD

**Issue by MrAgNO3** [wickedll/genshin_draw_analysis#4]
设置url正常

但是使用`draw_analysis`命令时提示
> visit too frequently

等一会儿再试的话，一样提示

**Comment by wickedll** [comment]
把draw_analysis.ts里面的sleep延时数值调高一点

**Comment by wickedll** [comment]
49行  调500-700  不行就再调大一点

**Comment by MrAgNO3** [comment]
已解决，感谢
