### ISSUE TITLE
抽卡次数过多导致抽卡记录分析插件无响应

### ISSUE THREAD

**Issue by weitanai123** [wickedll/genshin_draw_analysis#7]
有个氪佬氪了六千多抽……然后他绑定url成功，发了分析的命令，机器人没有任何反应，半分钟后直接回复图片渲染异常。
但是他的url在别的分析软件里可以正常得出结果![-5cca6bb8e1a09c99.png](https://user-images.githubusercontent.com/64584070/157207970-d21116bc-3bdf-4972-a5f9-09f2e1a09485.png)
附上氪佬的抽卡结果，太过震惊了导致没啥错误报告（本来也没啥）

**Comment by wickedll** [comment]
估计是颜色池的问题，我好像只设置了10几种颜色（忘记设置默认了），用完就没有了，你可以看看redis里面有没有他的抽卡数据，如果有的话  应该就是颜色池的问题
