### ISSUE TITLE
抽卡记录是不是可以保存起来？

### ISSUE THREAD

**Issue by BennettChina** [wickedll/genshin_draw_analysis#8]
如题，我发现第一次分析的抽卡记录隔了一段时间再次抽卡后去分析，差不多刚好我的武器池时间超过了半年，第二次分析便没有了武池的记录。所以是否可以将抽卡记录保存到数据库，而每次统计时拿出历史记录一起做统计，也算是给自己的抽卡记录做个保存。毕竟官方不保存半年以上的记录，我们可以自己保存嘛。

**Comment by wickedll** [comment]
这个我找时间调整一下看看
